lang: en-US
title: The Inner Citadel
email: andicabiri@gmail.com
description: Writing to think clearly
baseurl: ""
url: https://andicabiri.github.io
author:
  name: Andi Cabiri
  twitter: andicabiri
  picture: # add photo URL later
github_username: andicabiri
logo:
search: true
search_full_content: false

# Navigation
navigation:
  - title: Beyond the Multiple
    url: /beyond-the-multiple/
  - title: Thinking
    url: /thinking/

# Build settings
markdown: kramdown
remote_theme: mmistakes/jekyll-theme-basically-basic
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml
paginate: 10
paginate_path: /page:num/
exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README
  - vendor/
  - /docs
  - /example
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
